
links:

  default:

    ~/.aws: .aws
    ~/.bash_core: .bash_core
    ~/.bash_profile: .bash_profile
    ~/.bashrc: .bashrc
    ~/.bashrc.d: .bashrc.d
    ~/.inputrc: .inputrc
    ~/bin: bin
    ~/.gitconfig: .gitconfig
    ~/.profile: .profile
    ~/.tmux.conf: .tmux.conf


# EOF
