mkdirs:
  - ~/asdf
symlinks:
    ~/bin: bin
    ~/.bashrc: bashrc
    ~/.gitconfig: gitconfig
    ~/.tmux.conf: tmux.conf

script:
  - id: fix-ssh
    type: post
    command: |
      chmod 0400 ~/.ssh/config
      chmod 0400 ~/.ssh/config.d/*

# EOF
