mkdirs:
  - ~/asdf

symlinks:
    ~/bin: bin
    ~/.bashrc: bashrc
    ~/.gitconfig: gitconfig
    ~/.tmux.conf: tmux.conf

script:
  - id: fix-ssh-perms
    #type: post # This is the default if not given
    command: |
      chmod 0400 ~/.ssh/config
      chmod 0400 ~/.ssh/config.d/*
  - id: example-pre-script
    type: pre
    command: |
      mkdir -pv ~/random/stuff

walkdirs:
    ~/bin: bin

# EOF
